from langchain_core.messages import HumanMessage

from engine.agent.budget import BudgetTracker
from engine.agent.cost import CostTracker


def make_state(
    prompt: str,
    *,
    profile_decision: dict | None = None,
    task_profile: str = "general",
    capability_flags: list[str] | None = None,
    ambiguity_flags: list[str] | None = None,
    execution_template: dict | None = None,
    answer_contract: dict | None = None,
    evidence_pack: dict | None = None,
    assumption_ledger: list[dict] | None = None,
    provenance_map: dict | None = None,
    solver_stage: str = "PLAN",
    workpad: dict | None = None,
    pending_tool_call: dict | None = None,
    last_tool_result: dict | None = None,
    risk_feedback: dict | None = None,
    compliance_feedback: dict | None = None,
    review_feedback: dict | None = None,
    reflection_feedback: dict | None = None,
    checkpoint_stack: list[dict] | None = None,
    task_intent: dict | None = None,
    benchmark_overrides: dict | None = None,
    tool_plan: dict | None = None,
    source_bundle: dict | None = None,
    curated_context: dict | None = None,
    execution_journal: dict | None = None,
    quality_report: dict | None = None,
    review_packet: dict | None = None,
    progress_signature: dict | None = None,
    unsupported_capability_report: dict | None = None,
    fast_path_used: bool = False,
):
    return {
        "messages": [HumanMessage(content=prompt)],
        "profile_decision": profile_decision or {},
        "task_profile": task_profile,
        "capability_flags": capability_flags or [],
        "ambiguity_flags": ambiguity_flags or [],
        "execution_template": execution_template or {},
        "answer_contract": answer_contract or {},
        "evidence_pack": evidence_pack or {},
        "assumption_ledger": assumption_ledger or [],
        "provenance_map": provenance_map or {},
        "solver_stage": solver_stage,
        "workpad": workpad or {"events": [], "stage_outputs": {}, "tool_results": []},
        "pending_tool_call": pending_tool_call,
        "last_tool_result": last_tool_result,
        "risk_feedback": risk_feedback,
        "compliance_feedback": compliance_feedback,
        "review_feedback": review_feedback,
        "reflection_feedback": reflection_feedback,
        "checkpoint_stack": checkpoint_stack or [],
        "tool_fail_count": 0,
        "last_tool_signature": "",
        "budget_tracker": BudgetTracker(),
        "cost_tracker": CostTracker(),
        "memory_store": None,
        "task_intent": task_intent or {},
        "benchmark_overrides": benchmark_overrides or {},
        "tool_plan": tool_plan or {},
        "source_bundle": source_bundle or {},
        "curated_context": curated_context or {},
        "review_packet": review_packet or {},
        "execution_journal": execution_journal or {
            "events": [],
            "tool_results": [],
            "routed_tool_families": [],
            "revision_count": 0,
            "self_reflection_count": 0,
            "retrieval_iterations": 0,
            "retrieval_queries": [],
            "retrieved_citations": [],
            "final_artifact_signature": "",
            "progress_signatures": [],
            "stop_reason": "",
            "contract_collapse_attempts": 0,
        },
        "quality_report": quality_report or {},
        "progress_signature": progress_signature or {},
        "unsupported_capability_report": unsupported_capability_report or {},
        "fast_path_used": fast_path_used,
    }
