"""
Execution Template Library
==========================
Static, versioned execution templates selected deterministically at runtime.
"""

from __future__ import annotations

from agent.contracts import ExecutionTemplate, ExecutionTemplateId


TEMPLATE_LIBRARY: dict[ExecutionTemplateId, ExecutionTemplate] = {
    "quant_inline_exact": ExecutionTemplate(
        template_id="quant_inline_exact",
        description="Inline quantitative reasoning with exact computation from prompt-contained evidence.",
        allowed_stages=["COMPUTE", "SYNTHESIZE", "REVISE", "COMPLETE"],
        default_initial_stage="COMPUTE",
        allowed_tool_names=["calculator"],
        review_stages=["COMPUTE", "SYNTHESIZE"],
        review_cadence="milestone_and_final",
        answer_focus=[
            "Extract prompt-contained values exactly.",
            "Keep numeric computation compact and precise.",
            "Honor exact output contracts without narrative drift.",
        ],
        ambiguity_safe=True,
    ),
    "quant_with_tool_compute": ExecutionTemplate(
        template_id="quant_with_tool_compute",
        description="Quantitative reasoning that may require one evidence-gather or compute tool step before synthesis.",
        allowed_stages=["GATHER", "COMPUTE", "SYNTHESIZE", "REVISE", "COMPLETE"],
        default_initial_stage="COMPUTE",
        allowed_tool_names=[
            "calculator",
            "fetch_reference_file",
            "list_reference_files",
            "resolve_financial_entity",
            "get_price_history",
            "get_company_fundamentals",
            "get_corporate_actions",
            "get_yield_curve",
            "get_returns",
            "get_financial_statements",
            "get_statement_line_items",
            "weighted_average",
            "sum_values",
            "pct_change",
            "cagr",
            "annualize_return",
            "annualize_volatility",
            "bond_price_yield",
            "duration_convexity",
            "du_pont_analysis",
            "liquidity_ratio_pack",
            "valuation_multiples_compare",
            "dcf_sensitivity_grid",
            "cashflow_waterfall",
            "bond_spread_duration",
            "factor_exposure_summary",
            "drawdown_risk_profile",
            "liquidity_stress",
        ],
        review_stages=["GATHER", "COMPUTE", "SYNTHESIZE"],
        review_cadence="milestone_and_final",
        answer_focus=[
            "Use prompt evidence first, then targeted compute or file evidence if justified.",
            "Keep intermediate compute artifacts compact and reviewable.",
        ],
        ambiguity_safe=True,
    ),
    "regulated_actionable_finance": ExecutionTemplate(
        template_id="regulated_actionable_finance",
        description="Action-oriented finance recommendation that must remain source-backed and pass compliance before completion.",
        allowed_stages=["GATHER", "COMPUTE", "SYNTHESIZE", "REVISE", "COMPLETE"],
        default_initial_stage="GATHER",
        allowed_tool_names=[
            "resolve_financial_entity",
            "get_price_history",
            "get_company_fundamentals",
            "get_corporate_actions",
            "get_returns",
            "get_financial_statements",
            "get_statement_line_items",
            "liquidity_ratio_pack",
            "valuation_multiples_compare",
            "du_pont_analysis",
            "dcf_sensitivity_grid",
            "calculate_risk_metrics",
            "calculate_var",
            "run_stress_test",
        ],
        review_stages=["GATHER", "COMPUTE", "SYNTHESIZE"],
        review_cadence="milestone_and_final",
        answer_focus=[
            "Keep the recommendation explicitly tied to timestamped evidence.",
            "Carry recommendation class, key assumptions, and the main risk constraint into the final answer.",
            "Do not make unsupported action claims from stale or partial evidence.",
        ],
    ),
    "equity_research_report": ExecutionTemplate(
        template_id="equity_research_report",
        description="Equity research workflow grounded in fundamentals, market context, valuation operators, and explicit risk summary.",
        allowed_stages=["GATHER", "COMPUTE", "SYNTHESIZE", "REVISE", "COMPLETE"],
        default_initial_stage="GATHER",
        allowed_tool_names=[
            "resolve_financial_entity",
            "get_company_fundamentals",
            "get_price_history",
            "get_returns",
            "get_corporate_actions",
            "get_financial_statements",
            "get_statement_line_items",
            "du_pont_analysis",
            "valuation_multiples_compare",
            "dcf_sensitivity_grid",
            "cashflow_waterfall",
            "calculate_risk_metrics",
            "drawdown_risk_profile",
        ],
        review_stages=["GATHER", "COMPUTE", "SYNTHESIZE"],
        review_cadence="milestone_and_final",
        answer_focus=[
            "Produce a real research note, not a generic summary.",
            "Keep thesis, evidence, valuation, catalysts, and risk summary explicit.",
            "Anchor claims in timestamped structured evidence wherever possible.",
        ],
    ),
    "portfolio_risk_review": ExecutionTemplate(
        template_id="portfolio_risk_review",
        description="Portfolio risk workflow for exposures, concentration, scenario stress, limit checks, and recommended actions.",
        allowed_stages=["COMPUTE", "SYNTHESIZE", "REVISE", "COMPLETE"],
        default_initial_stage="COMPUTE",
        allowed_tool_names=[
            "concentration_check",
            "factor_exposure_summary",
            "drawdown_risk_profile",
            "liquidity_stress",
            "calculate_risk_metrics",
            "calculate_var",
            "portfolio_limit_check",
            "run_stress_test",
            "get_price_history",
            "get_returns",
            "fetch_reference_file",
            "list_reference_files",
        ],
        review_stages=["COMPUTE", "SYNTHESIZE"],
        review_cadence="milestone_and_final",
        answer_focus=[
            "State the main exposure concentrations first.",
            "Include scenario or stress evidence before final recommendations.",
            "Convert risk findings into concrete rebalance, trim, hedge, or hold actions.",
        ],
    ),
    "event_driven_finance": ExecutionTemplate(
        template_id="event_driven_finance",
        description="Event-driven finance workflow for catalyst-sensitive analysis using market evidence and corporate-action context.",
        allowed_stages=["GATHER", "COMPUTE", "SYNTHESIZE", "REVISE", "COMPLETE"],
        default_initial_stage="GATHER",
        allowed_tool_names=[
            "resolve_financial_entity",
            "get_price_history",
            "get_returns",
            "get_corporate_actions",
            "get_company_fundamentals",
            "get_financial_statements",
            "get_statement_line_items",
            "calculate_risk_metrics",
            "run_stress_test",
        ],
        review_stages=["GATHER", "COMPUTE", "SYNTHESIZE"],
        review_cadence="milestone_and_final",
        answer_focus=[
            "Explain the event or catalyst clearly before giving an action view.",
            "Use scenario framing: base, upside, downside, stress.",
            "Keep timestamped evidence and event-specific risk factors explicit.",
        ],
    ),
    "options_tool_backed": ExecutionTemplate(
        template_id="options_tool_backed",
        description="Options workflow requiring structured tool-backed compute before final synthesis.",
        allowed_stages=["COMPUTE", "SYNTHESIZE", "REVISE", "COMPLETE"],
        default_initial_stage="COMPUTE",
        allowed_tool_names=[
            "calculator",
            "black_scholes_price",
            "option_greeks",
            "mispricing_analysis",
            "analyze_strategy",
            "scenario_pnl",
            "calculate_var",
            "run_stress_test",
            "portfolio_limit_check",
            "concentration_check",
            "calculate_portfolio_greeks",
            "get_options_chain",
            "get_iv_surface",
            "get_expirations",
            "resolve_financial_entity",
            "get_price_history",
            "get_returns",
            "fetch_reference_file",
            "list_reference_files",
        ],
        review_stages=["COMPUTE", "SYNTHESIZE"],
        review_cadence="milestone_and_final",
        answer_focus=[
            "Ground the primary strategy in structured tool results.",
            "Add at least one scenario or stress analysis before final synthesis.",
            "Compare at least one alternative with concrete tradeoffs.",
            "Keep Greeks, premium direction, breakevens, risk controls, and required disclosures explicit.",
            "Respect any explicit mandate constraints from the prompt before the final answer is accepted.",
        ],
    ),
    "legal_reasoning_only": ExecutionTemplate(
        template_id="legal_reasoning_only",
        description="Transactional legal reasoning with no routine external retrieval or file evidence.",
        allowed_stages=["COMPUTE", "SYNTHESIZE", "REVISE", "COMPLETE"],
        default_initial_stage="SYNTHESIZE",
        allowed_tool_names=["calculator"],
        review_stages=["SYNTHESIZE"],
        review_cadence="final_only",
        answer_focus=[
            "Cover structure, tax, liability, diligence, assumptions, and next steps.",
            "Do not invent authorities or source documents.",
        ],
        ambiguity_safe=True,
    ),
    "legal_with_document_evidence": ExecutionTemplate(
        template_id="legal_with_document_evidence",
        description="Transactional legal reasoning supported by targeted document evidence.",
        allowed_stages=["GATHER", "SYNTHESIZE", "REVISE", "COMPLETE"],
        default_initial_stage="GATHER",
        allowed_tool_names=["calculator", "fetch_reference_file", "list_reference_files"],
        review_stages=["GATHER", "SYNTHESIZE"],
        review_cadence="milestone_and_final",
        answer_focus=[
            "Retrieve only targeted document evidence and preserve source references.",
            "Start with metadata or a narrow extraction window before deeper reads.",
            "Synthesize legal structure tradeoffs without raw document dumping.",
        ],
        ambiguity_safe=True,
    ),
    "document_qa": ExecutionTemplate(
        template_id="document_qa",
        description="Document-grounded QA with targeted evidence gathering first.",
        allowed_stages=["GATHER", "SYNTHESIZE", "REVISE", "COMPLETE"],
        default_initial_stage="GATHER",
        allowed_tool_names=["calculator", "fetch_reference_file", "list_reference_files"],
        review_stages=["GATHER", "SYNTHESIZE"],
        review_cadence="milestone_and_final",
        answer_focus=[
            "Ground the answer in extracted evidence.",
            "Start with a narrow extraction window instead of pulling the whole document body.",
            "Prefer evidence summaries and source references over raw excerpts.",
        ],
        ambiguity_safe=True,
    ),
    "live_retrieval": ExecutionTemplate(
        template_id="live_retrieval",
        description="Explicit current-data retrieval followed by concise synthesis with sources.",
        allowed_stages=["GATHER", "SYNTHESIZE", "REVISE", "COMPLETE"],
        default_initial_stage="GATHER",
        allowed_tool_names=[
            "internet_search",
            "fetch_reference_file",
            "list_reference_files",
            "calculator",
            "resolve_financial_entity",
            "get_price_history",
            "get_company_fundamentals",
            "get_corporate_actions",
            "get_yield_curve",
            "get_returns",
            "get_financial_statements",
            "get_statement_line_items",
        ],
        review_stages=["GATHER", "SYNTHESIZE"],
        review_cadence="milestone_and_final",
        answer_focus=[
            "Retrieve current facts only when explicitly requested.",
            "Keep sources visible and avoid unsupported extrapolation.",
        ],
        ambiguity_safe=True,
    ),
}


def get_execution_template(template_id: str) -> ExecutionTemplate:
    return TEMPLATE_LIBRARY.get(template_id, TEMPLATE_LIBRARY["legal_reasoning_only"])
